version: '3.8'

services:
    localstack:
        network_mode:   bridge
        image:          localstack/localstack
        container_name: localstack-example
        hostname:       localstack
        ports:
            - "4566:4566"
        environment:
            # Declare which aws services will be used in localstack
            - SERVICES=iam,s3,lambda,cloudwatch,events,cloudwatchevents
            - DEBUG=1
            # These variables are needed for localstack
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_ACCESS_KEY_ID=testUser
            - AWS_SECRET_ACCESS_KEY=testAccessKey
            - LAMBDA_EXECUTOR=local
            - DOCKER_HOST=unix:///var/run/docker.sock
            - DATA_DIR=/var/lib/localstack/data
        volumes:
            - "${TMPDIR:-/tmp}/localstack:/var/lib/localstack"
            - /var/run/docker.sock:/var/run/docker.sock
            - ./target/lambda-spike-0.0.1-SNAPSHOT.jar:/lambdas.jar
            - ./create-resources.sh:/docker-entrypoint-initaws.d/create-resources.sh
